"""Auto-generated postmortem.

Turns the incident's own audit trail (what was detected, diagnosed, proposed,
authorized, executed, and verified) into a reviewable markdown postmortem -- the
kind an on-call engineer would otherwise write by hand. Deterministic: it reads
the recorded facts, so it needs no LLM and always matches what actually happened.
"""

from __future__ import annotations

from typing import Any

from incidentpilot.models import Incident


def render_postmortem(incident: Incident, report: dict[str, Any]) -> str:
    """Render a markdown postmortem from an incident + its workflow `report` event.

    `report` keys (all optional): cause, confidence, action, blast_radius,
    allowed, requires_approval, approved, executed, resolved, metrics_after,
    evidence (list of {tool, summary}).
    """

    resolved = bool(report.get("resolved"))
    status = "Resolved" if resolved else "Unresolved"
    cause = report.get("cause", "undetermined")
    action = report.get("action", "none")
    conf = report.get("confidence")
    conf_str = f" (confidence {conf})" if conf is not None else ""

    lines: list[str] = []
    lines.append(f"# Incident postmortem — {incident.id}")
    lines.append("")
    lines.append(
        f"**Service:** `{incident.service}`  ·  **Severity:** {incident.severity}  ·  "
        f"**Status:** {status}"
    )
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append(
        f"`{incident.metric}` broke from a baseline of {incident.baseline:.3g} to "
        f"{incident.value:.3g} (robust z-score {incident.z_score:.1f}). "
        f"Diagnosis: {cause}{conf_str}. "
        + (
            f"Remediation `{action}` was applied and the signal recovered."
            if resolved
            else f"Remediation `{action}` did not resolve the incident."
        )
    )
    lines.append("")

    # Root cause + evidence
    lines.append("## Root cause")
    lines.append(cause + conf_str)
    evidence = report.get("evidence") or []
    if evidence:
        lines.append("")
        lines.append("**Evidence**")
        for e in evidence:
            lines.append(f"- `{e.get('tool', '?')}` — {e.get('summary', '')}")
    lines.append("")

    # Remediation + authorization (the safety story)
    lines.append("## Remediation & authorization")
    br = report.get("blast_radius")
    br_str = f" (blast radius {br})" if br is not None else ""
    lines.append(f"- Proposed action: `{action}`{br_str}")
    lines.append(f"- Policy decision: {'allowed' if report.get('allowed') else 'denied'}")
    if report.get("requires_approval"):
        lines.append(
            f"- Human approval: {'granted' if report.get('approved') else 'not granted'} "
            "(required — high blast radius)"
        )
    else:
        lines.append("- Human approval: not required (within auto-remediation policy)")
    lines.append(f"- Executed: {'yes' if report.get('executed') else 'no'}")
    lines.append("")

    # Verification
    lines.append("## Verification")
    after = report.get("metrics_after") or {}
    if resolved and after:
        pairs = ", ".join(f"`{k}` = {v}" for k, v in after.items())
        lines.append(f"Post-action check confirmed recovery: {pairs}.")
    elif resolved:
        lines.append("Post-action check confirmed the signal recovered.")
    else:
        lines.append("Post-action check did **not** confirm recovery; the action was rolled back.")
    lines.append("")

    # Follow-ups
    lines.append("## Follow-ups")
    lines.append("- [ ] Add an alert/guardrail so this fault class is caught earlier.")
    lines.append("- [ ] Review whether this remediation can graduate to auto (per problem type).")
    lines.append("- [ ] Backfill a runbook entry if one was missing.")
    lines.append("")
    lines.append("_Generated by IncidentPilot from the incident's audit trail._")
    return "\n".join(lines)
